### ISSUE TITLE
Broken in 1.9.0

### ISSUE THREAD

**Issue by gshaw** [lafe/ContextualDuplicate#2] opened 2017-02-04 22:45 UTC
- VSCode Version: 1.9.0
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Ensure you have an empty `.vscode/tasks.json` file.  E.g., `touch ~/.vscode/tasks.json`.
2. Use extension via command palette or bound key.

Expected: Current line or selected text to duplicate as it did in 1.8.1.

Actual: Nothing happens (and file saving is delayed by a few seconds).

Workaround: Remove empty `.vscode/tasks.json` file.

**Comment by lafe** [comment] 2017-02-07 17:07
I just tried to reproduce the issue and unfortunately, I was not able to. However, I do not have access to a Mac, so I could only test it with Windows 10. For me, the current version works with 1.9.0 and the current insiders build of 1.10 on Windows.
Do you have further information that help to track down the issue?

**Comment by gshaw** [comment] 2017-02-07 17:25
It's related to microsoft/vscode#19945.

If you have an empty `.vscode/tasks.json` file the extension stops working.  The problem goes away by deleting the empty tasks.json file.  It might be possible that the fix they have in microsoft/vscode#19773 will also solve this.

I've updated the steps to reproduce in the issue description.

**Comment by lafe** [comment] 2017-02-07 17:44
Thanks for the additional information. I was able to confirm the issue in 1.9. In the current Insiders Build, the issue is already fixed, so it is likely related to the issues mentioned above. As this seems to be an issue with VSCode itself and because there is a 1.9.1 bugfix on the way, I will close this issue for now.
Please let me know, if the issue should persist after updating to 1.9.1.

**Closed as completed by lafe** 2017-02-07 17:44 UTC
